version: '3.8'

services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: Canada
      MYSQL_DATABASE: mibase1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
